services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - '5555:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  wol_webui:
    container_name: wol_webui
    image: wol_webui
    build: .
    network_mode: 'host'

volumes:
  pg_data:
